### ISSUE TITLE
Pictures of trumpets (and strumpets) are erronously replaced with kittens

### ISSUE THREAD

**Issue by kzar** [tomroyal/Make-America-Kittens-Again#10]
## Steps to reproduce
1. Do a Google image search for "trumpet".
2. Notice that the trumpet pictures are replaced with kittens, despite not containing Donald Trump.

## Problem
It seems to be down to the logic which decides if a picture contains Trump or not:
```(alttext.indexOf("trump") != -1) || (imgsrc.indexOf("trump") != -1) || (parenttag.indexOf("trump") != -1)```

## Solution
Perhaps we could instead use a regular expression? Here's a simplistic one `/[^a-z]trump[^a-z]/ig` that works a bit better than the existing logic. However note that it won't match a string starting or ending with the string "trump".

**Comment by tomroyal** [comment]
Hi! It's a balance between false positives and false negatives, unfortunately. I tried using only (for example) "Trump" followed by space, comma, full stop, etc - to avoid, say "trumpet" - but the match rate was too low - people don't often supply good alt-tags, and filenames didn't match. Matching "trump" with * on either side sometimes produces false positives, but generally that seems more preferable - have now added an "undo" function for those occasions.
