### ISSUE TITLE
Move images inside the extension itself?

### ISSUE THREAD

**Issue by kzar** [tomroyal/Make-America-Kittens-Again#11]
Instead of pointing the extension at your own (AWS) server to fetch the kitten images, why not simply include the images in the extension itself? That would be more responsive during browsing for people with slow connections and depending on how long the images are cached it could save the end user bandwidth as well.

**Comment by tomroyal** [comment]
This was by design - wanted to keep the extension filesize down, the images are quite chunky. And they get cached by Chrome, so after the initial rush of installs S3 data transfer is calming down. But will give it another look - thanks.

**Comment by tomroyal** [comment]
So after another couple of months of crazy server traffic, I did indeed have another look at this - and it's now done; images are stored internally. Will see how this goes. Thanks!
