### ISSUE TITLE
Change Icon Please

### ISSUE THREAD

**Issue by fortjohnson** [tomroyal/Make-America-Kittens-Again#12]
I don't want people mistaking it for a Making America Great Again especially since I give presentations fairly often from my browser.

Thanks!

**Comment by pegship** [comment]
You can remove the icon entirely by right-clicking on it and selecting "Hide in Chrome menu" -
![screen shot 2017-02-01 at 10 47 20 am](https://cloud.githubusercontent.com/assets/25489266/22521270/587fdae2-e86c-11e6-8674-82b12ed14a35.png)

**Comment by tomroyal** [comment]
pegship - thanks, I didn't know that was an option!

fortjohnson - you're not the only person to have requested this; I'd like to do it but need to come up with a good replacement; will re-open this thread if/when the live version updates to fix.

**Comment by fortjohnson** [comment]
Thanks @pegship I should have looked there first!
