### ISSUE TITLE
Please upload to addons.mozilla.org so that Firefox users can use it as well.

### ISSUE THREAD

**Issue by nl255** [tomroyal/Make-America-Kittens-Again#16]
Now that Firefox has support for Chrome style extensions it would be nice to see it available on addons.mozilla.org for Firefox users.  While it is possible to install it using Chrome Store Foxified and works perfectly (tested in Firefox 50.1.0) doing so requires the user to create a developer account on AMO so that they can get it signed otherwise it won't stay installed past the current session.  

Fortunately, porting the extension to Firefox should be as simple as adding a single item to manifest.json, packaging it as an .xpi, and uploading it.  I have included a Firefox compatible .xpi (which was automatically converted from the chrome store version) if you want to take a look though keep in mind that it is unsigned and thus can only be temporairly installed.

[Make America Kittens Again - Version 1.1.4 - UNSIGNED.zip](https://github.com/tomroyal/Make-America-Kittens-Again/files/852742/Make.America.Kittens.Again.-.Version.1.1.4.-.UNSIGNED.zip)

**Comment by andreicristianpetcu** [comment]
I made a [unlisted signed build](https://github.com/andreicristianpetcu/Make-America-Kittens-Again/releases/download/v1.2.2.1/make_america_kittens_again-1.2.2-an.fx.xpi).

Please @tomroyal just zip it and [upload it to AMO](https://addons.mozilla.org/en-US/developers/addon/submit/distribution). It takes 1 minute.

**Comment by tomroyal** [comment]
Thanks, both. I'm afraid I don't plan to support a Firefox version going forward; the new FF extension system looks like it should be easy for anyone who wants to roll their own plugin from the code.

**Comment by andreicristianpetcu** [comment]
"Please feel free to copy / edit / reuse the code in any way you like, but please do not use my hosted kitten images - I have to pay the S3 bill each month ;)" https://github.com/tomroyal/Make-America-Kittens-Again#make-america-kittens-again

Not sure if I would pay an AWS server just for this... :( If we can't use yours then I do not intend to make a Firefox port.

**Comment by andreicristianpetcu** [comment]
"Please feel free to copy / edit / reuse the code in any way you like, but please do not use my hosted kitten images - I have to pay the S3 bill each month ;)" https://github.com/tomroyal/Make-America-Kittens-Again#make-america-kittens-again

Not sure if I would pay and maintain an AWS server just for this... :( If we can't use yours then I do not intend to make a Firefox port.

**Comment by tomroyal** [comment]
See: https://github.com/tomroyal/Make-America-Kittens-Again/blob/4a4610882c533326716e3012af910321b0b00288/maka.js#L171
