### ISSUE TITLE
console logs

### ISSUE THREAD

**Issue by emilymaskin** [tomroyal/Make-America-Kittens-Again#17]
Could you turn off the console logs? (Looks like we're in debug mode...?) They're getting in the way of my own debugging :) and I would be SO SAD to turn off the extension because it's my favorite thing ever.

**Comment by tomroyal** [comment]
Sorry about that - dumb mistake on my part; I left the debug flag set to "true" when deploying. Will push an updated version shortly.

In the meantime - if you download this repo and edit line 6 of maka.js, you'll be able to run the fixed version immediately :)

**Comment by emilymaskin** [comment]
awesome, thanks!

**Comment by kenhowardpdx** [comment]
@tomroyal I left a comment on your blog. Sorry. This is the better place to report this :)

**Comment by tomroyal** [comment]
Emily - sure thing!

Ken - no problem at all.

And this bug is fixed in version 1.2.1, which should be going live about now - sorry again for the error.
