### ISSUE TITLE
Suggestion: Look for text inside element

### ISSUE THREAD

**Issue by mskogly** [tomroyal/Make-America-Kittens-Again#2]
<div>
<img src="123.jpg"/>
Trump is weird.
</div>

Most sites I've tested used generic filenames and no mention of trump in the alt-tag, so how about doing a child-parent mapping to get a better result.

Love the plugin, already made me happy twice today.

**Comment by tomroyal** [comment]
Thanks! What the current version does is check everything inside the parent, using innerhtml, so not just the filename and alt - I think the current failures are usually caused by "srcset" attributes, which I'm working to fix.

**Comment by tomroyal** [comment]
.. and this is fixed as of v1.1.2, hopefully :)
