### ISSUE TITLE
Intermittent with latest Chrome update.

### ISSUE THREAD

**Issue by Fiddlegirl** [tomroyal/Make-America-Kittens-Again#29]
After I updated Chrome, Version 73.0.3683.103 (Official Build) (64-bit), the extension doesn't always work.

**Comment by tomroyal** [comment]
Hi! Thanks for letting me know. I'm not seeing this myself (73.0.3683.103, 64, OSX) - do you have an example of a URL where it's not working for you that I could check out please? Thanks again.

**Comment by Fiddlegirl** [comment]
Where I use it most often is dailykos.com <http://dailykos.com/>. However, things seem back to normal. Maybe it was just a bug that day, or an unusually high number of Trump pictures with no tag. Sorry to bother you.

**Comment by tomroyal** [comment]
No problem! Thanks for the report; I'll close this for now but can re-open if it occurs again.
