### ISSUE TITLE
BBC: Should work

### ISSUE THREAD

**Issue by mskogly** [tomroyal/Make-America-Kittens-Again#3]
This is an image on BBC.co.uk right now. Should work, but no kitten. Perhaps strip ()?

<img src="http://ichef.bbci.co.uk/wwhp/624/cpsprodpb/45ED/production/_93210971_mediaitem93210970.jpg" class="image-replace" alt="Donald Trump (file photo)" data-src="http://ichef.bbci.co.uk/wwhp/{width}/cpsprodpb/45ED/production/_93210971_mediaitem93210970.jpg">

**Comment by tomroyal** [comment]
Thanks - on the BBC site this is usually a case of MAKA replacing the image src, but not srcset attributes - the current commit should fix it, and will be published once tested.
